### ISSUE TITLE
Missing dependence

### ISSUE THREAD

**Issue by Jiefei-Wang** [daviden1013/ie-viz#1]
You use `flask_socketio` here

 https://github.com/daviden1013/ie-viz/blob/fab0f4f0f5cf044ee4421a67349155780cf86ba1/src/ie_viz/utilities.py#L5

I think you also need to declare `flask_socketio` as your dependence
https://github.com/daviden1013/ie-viz/blob/fab0f4f0f5cf044ee4421a67349155780cf86ba1/pyproject.toml#L16

**Comment by daviden1013** [comment]
Thanks, I've added dependence for Flask-SocketIO in the new version.
